# 딥러닝 따라하기2_분류

* 목적 : 무작정 따라하면서 코드 눈과 손으로 익히기

# 1.환경준비

* 라이브러리 Import

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import *
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# 2.Classification : 대학원 지원

## (1) 데이터 전처리

### 1) 데이터 준비

In [2]:
path = "https://raw.githubusercontent.com/DA4BAM/dataset/master/Graduate_apply.csv"
data = pd.read_csv(path)
data.head()

admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4

In [3]:
target = 'admit'
x = data.drop(target, axis=1)
y = data.loc[:, target]

### 2) 가변수화

### 3) 데이터분할

In [4]:
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=.2, random_state = 20)

## (2) 머신러닝 모델링 : 로지스틱회귀

In [6]:
# 필요한 알고리즘을 불러 옵시다.
from sklearn.linear_model import LogisticRegression

### 1) 모델 선언

In [7]:
model = LogisticRegression()

### 2) 학습

In [8]:
model.fit(x_train, y_train)

LogisticRegression()

### 3) 예측

In [10]:
pred = model.predict(x_val)

### 4) 검증
만든 모델은 얼마나 정확한지 검증해 봅시다.



In [11]:
print(confusion_matrix(y_val, pred))
print('-'*50)
print(classification_report(y_val, pred))

[[48  7]
 [18  7]]
--------------------------------------------------
              precision    recall  f1-score   support

           0       0.73      0.87      0.79        55
           1       0.50      0.28      0.36        25

    accuracy                           0.69        80
   macro avg       0.61      0.58      0.58        80
weighted avg       0.66      0.69      0.66        80



## (3) 딥러닝 모델링
* 필요한 함수들 불러오기
* 모델 선언
* 학습
* 예측
* 성능 검증

### 1) 전처리 : Scaling

In [ ]:
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_val = scaler.transform(x_val)

### 2) 필요한 함수 불러오기

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.backend import clear_session

### 3) 모델 선언

In [ ]:
nfeatures = x_train.shape[1] #num of columns
nfeatures

5

In [ ]:
# 메모리 정리
clear_session()

# Sequential 타입 모델 선언
model = Sequential([ Dense(1, input_shape = (nfeatures,), activation = 'sigmoid' ) ])

# 모델요약
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 6         
                                                                 
Total params: 6
Trainable params: 6
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer='adam', loss= 'binary_crossentropy')

### 4) 학습

In [ ]:
model.fit(x_train, y_train)

10/10 [==============================] - 1s 3ms/step - loss: 0.6546


### 5) 예측

In [ ]:
pred = model.predict(x_val)
pred = np.where(pred>= 0.5, 1, 0)

3/3 [==============================] - 0s 4ms/step


### 6) 검증
만든 모델은 얼마나 정확한지 검증해 봅시다.



In [ ]:
print(confusion_matrix(y_val, pred))
print('-'*50)
print(classification_report(y_val, pred))

[[52  3]
 [22  3]]
--------------------------------------------------
              precision    recall  f1-score   support

           0       0.70      0.95      0.81        55
           1       0.50      0.12      0.19        25

    accuracy                           0.69        80
   macro avg       0.60      0.53      0.50        80
weighted avg       0.64      0.69      0.61        80



# 3.Classification : mobile

## (1) 데이터 전처리

### 1) 데이터 준비

In [ ]:
path = "https://raw.githubusercontent.com/DA4BAM/dataset/master/mobile_churn_simple.csv"
data = pd.read_csv(path)
data['CHURN'] = data['CHURN'].map({'STAY':0, 'LEAVE':1})
data.head()

INCOME  OVERAGE  LEFTOVER   HOUSE  HANDSET_PRICE  \
0   31953        0         6  313378            161   
1   36147        0        13  800586            244   
2   27273      230         0  305049            201   
3  120070       38        33  788235            780   
4   29215      208        85  224784            241   

   OVER_15MINS_CALLS_PER_MONTH  AVERAGE_CALL_DURATION  CHURN  
0                            0                      4      0  
1                            0                      6      0  
2                           16                     15      0  
3                            3                      2      1  
4                           21                      1      0

|	구분	|	변수 명	|	내용	|	type	|	비고	|
|	----	|	----	|	----	|	----	|	----	|
|	**Target**	|	**CHURN**	|	이탈여부	|	범주	| 0,1	|
|	feature	|	INCOME	|	소득수준(달러)	|	숫자	|		|
|	feature	|	OVERAGE	|	월평균 초과사용시간(분)	|	숫자	| |
|	feature	|	LEFTOVER	|	월평균 잔여시간(%)	|	숫자	| 	|
|	feature	|	HOUSE	|	집가격(달러)	|	숫자	|	|
|	feature	|	HANDSET_PRICE	|	휴대폰가격(달러)	|	숫자	|		|
|	feature	|	OVER_15MINS_CALLS_PER_MONTH	|	월평균 장기통화 횟수	|	숫자	| 		|
|	feature	|	AVERAGE_CALL_DURATION	|	평균통화시간(분)	|	숫자	|		|

In [ ]:
target = 'CHURN'
x = data.drop(target, axis=1)
y = data.loc[:, target]

### 2) 가변수화

### 3) 데이터분할

In [ ]:
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=.2, random_state = 20)

### 4) Scaling

In [ ]:
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_val = scaler.transform(x_val)

## (2) 모델링
* 필요한 함수들 불러오기
* 모델 선언
* 학습
* 예측
* 성능 검증

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.backend import clear_session

### 1) 모델 선언

In [ ]:
nfeatures = x_train.shape[1] #num of columns
nfeatures

7

In [ ]:
# 메모리 정리
clear_session()

# Sequential 타입 모델 선언
model = Sequential([ Dense(1, input_shape = (nfeatures,), activation = 'sigmoid') ])

# 모델요약
model.summary()

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy')

### 2) 학습

In [ ]:
model.fit(x_train, y_train)

### 3) 예측

In [ ]:
pred = model.predict(x_val)
pred

In [ ]:
pred = np.where(pred>= 0.5, 1, 0)

### 4) 검증
만든 모델은 얼마나 정확한지 검증해 봅시다.



In [ ]:
print(confusion_matrix(y_val, pred))
print('-'*50)
print(classification_report(y_val, pred))

[[1217  821]
 [ 710 1252]]
--------------------------------------------------
              precision    recall  f1-score   support

           0       0.63      0.60      0.61      2038
           1       0.60      0.64      0.62      1962

    accuracy                           0.62      4000
   macro avg       0.62      0.62      0.62      4000
weighted avg       0.62      0.62      0.62      4000

